module.exports = [
  {
    character: '&#x221E;',
    glyph: '∞',
    latex: '\\infty',
    name: 'infinity',
  },
  {
    character: '&#x3B1;',
    glyph: 'α',
    latex: '\\alpha',
    name: 'alpha greek letter',
  },
  {
    character: '&#x3B2;',
    glyph: 'β',
    latex: '\\beta',
    name: 'beta greek letter',
  },
  {
    character: '&#x3B3;',
    glyph: 'γ',
    latex: '\\gamma',
    name: 'gamma greek letter',
  },
  {
    character: '&#x393;',
    glyph: 'Γ',
    latex: '\\Gamma',
    name: 'capital gamma greek letter',
  },
  {
    character: '&#x3B4;',
    glyph: 'δ',
    latex: '\\delta',
    name: 'delta greek letter',
  },
  {
    character: '&#x394;',
    glyph: 'Δ',
    latex: '\\Delta',
    name: 'capital delta greek letter',
  },
  {
    character: '&#x3B5;',
    glyph: 'ε',
    latex: '\\epsilon',
    name: 'epsilon greek letter',
  },
  {
    character: '&#x25B;',
    glyph: 'ɛ',
    latex: '\\varepsilon',
    name: 'varepsilon greek letter',
  },
  {
    character: '&#x3B6;',
    glyph: 'ζ',
    latex: '\\zeta',
    name: 'zeta greek letter',
  },
  {
    character: '&#x3B7;',
    glyph: 'η',
    latex: '\\eta',
    name: 'eta greek letter',
  },
  {
    character: '&#x3B8;',
    glyph: 'θ',
    latex: '\\theta',
    name: 'theta greek letter',
  },
  {
    character: '&#x398;',
    glyph: 'Θ',
    latex: '\\Theta',
    name: 'capital theta greek letter',
  },
  {
    character: '&#x3D1;',
    glyph: 'ϑ',
    latex: '\\vartheta',
    name: 'vartheta greek letter',
  },
  {
    character: '&#x3B9;',
    glyph: 'ι',
    latex: '\\iota',
    name: 'iota greek letter',
  },
  {
    character: '&#x3BA;',
    glyph: 'κ',
    latex: '\\kappa',
    name: 'kappa greek letter',
  },
  {
    character: '&#x3BB;',
    glyph: 'λ',
    latex: '\\lambda',
    name: 'lambda greek letter',
  },
  {
    character: '&#x39B;',
    glyph: 'Λ',
    latex: '\\Lambda',
    name: 'capital lambda greek letter',
  },
  {
    character: '&#x3BC;',
    glyph: 'μ',
    latex: '\\mu',
    name: 'mu greek letter',
  },
  {
    character: '&#x3BD;',
    glyph: 'ν',
    latex: '\\nu',
    name: 'nu greek letter',
  },
  {
    character: '&#x3BE;',
    glyph: 'ξ',
    latex: '\\xi',
    name: 'xi greek letter',
  },
  {
    character: '&#x39E;',
    glyph: 'Ξ',
    latex: '\\Xi',
    name: 'capital xi greek letter',
  },
  {
    character: '&#x3C0;',
    glyph: 'π',
    latex: '\\pi',
    name: 'pi greek letter',
  },
  {
    character: '&#x3A0;',
    glyph: 'Π',
    latex: '\\Pi',
    name: 'capital pi greek letter',
  },
  {
    character: '&#x3C1;',
    glyph: 'ρ',
    latex: '\\rho',
    name: 'rho greek letter',
  },
  {
    character: '&#x3C3;',
    glyph: 'σ',
    latex: '\\sigma',
    name: 'sigma greek letter',
  },
  {
    character: '&#x3A3;',
    glyph: 'Σ',
    latex: '\\Sigma',
    name: 'capital sigma greek letter',
  },
  {
    character: '&#x3C4;',
    glyph: 'τ',
    latex: '\\tau',
    name: 'tau greek letter',
  },
  {
    character: '&#x3C5;',
    glyph: 'υ',
    latex: '\\upsilon',
    name: 'upsilon greek letter',
  },
  {
    character: '&#x3D5;',
    glyph: 'ϕ',
    latex: '\\phi',
    name: 'phi greek letter',
  },
  {
    character: '&#x3A6;',
    glyph: 'Φ',
    latex: '\\Phi',
    name: 'capital phi greek letter',
  },
  {
    character: '&#x3C6;',
    glyph: 'φ',
    latex: '\\varphi',
    name: 'varphi greek letter',
  },
  {
    character: '&#x3C7;',
    glyph: 'χ',
    latex: '\\chi',
    name: 'chi greek letter',
  },
  {
    character: '&#x3C8;',
    glyph: 'ψ',
    latex: '\\psi',
    name: 'psi greek letter',
  },
  {
    character: '&#x3A8;',
    glyph: 'Ψ',
    latex: '\\Psi',
    name: 'capital psi greek letter',
  },
  {
    character: '&#x3C9;',
    glyph: 'ω',
    latex: '\\omega',
    name: 'omega greek letter',
  },
  {
    character: '&#x3A9;',
    glyph: 'Ω',
    latex: '\\Omega',
    name: 'capital omega greek letter',
  },
  {
    character: '&#x22C5;',
    glyph: '⋅',
    latex: '\\cdot',
    name: 'center dot',
  },
  {
    character: '&#x2217;',
    glyph: '∗',
    latex: '\\star',
    name: 'asterisk',
  },
  {
    character: '&#x22C6;',
    glyph: '⋆',
    latex: '\\star',
    name: 'star',
  },
  {
    character: '\\',
    glyph: '\\',
    latex: '\\backslash',
    name: 'backslash',
  },
  {
    character: '&#xD7;',
    glyph: '×',
    latex: '\\times',
    name: 'times',
  },
  {
    character: '&#xF7;',
    glyph: '÷',
    latex: '\\div',
    name: 'division',
  },
  {
    character: '&#x22C9;',
    glyph: '⋉',
    latex: '\\ltimes',
    name: 'left normal factor semidirect product',
  },
  {
    character: '&#x22CA;',
    glyph: '⋊',
    latex: '\\rtimes',
    name: 'right normal factor semidirect product',
  },
  {
    character: '&#x22C8;',
    glyph: '⋈',
    latex: '\\bowtie',
    name: 'bowtie',
  },
  {
    character: '&#x2218;',
    glyph: '∘',
    latex: '@',
    name: '\\circ',
  },
  {
    character: '&#x2295;',
    glyph: '⊕',
    latex: 'o+',
    name: 'circled plus',
  },
  {
    character: '&#x2297;',
    glyph: '⊗',
    latex: '\\bigoplus',
    name: 'circled times',
  },
  {
    character: '&#x2299;',
    glyph: '⊙',
    latex: '\\bigodot',
    name: 'circled dot',
  },
  {
    character: '&#x2211;',
    glyph: '∑',
    latex: '\\sum',
    name: 'summatory',
  },
  {
    character: '&#x220F;',
    glyph: '∏',
    latex: '\\prod',
    name: 'productory',
  },
  {
    character: '&#x2227;',
    glyph: '∧',
    latex: '\\wedge',
    name: 'wedge',
  },
  {
    character: '&#x22C0;',
    glyph: '⋀',
    latex: '\\wedge',
    name: 'big wedge',
  },
  {
    character: '&#x2228;',
    glyph: '∨',
    latex: '\\vee',
    name: 'vee',
  },
  {
    character: '&#x22C1;',
    glyph: '⋁',
    latex: '\\vee',
    name: 'big vee',
  },
  {
    character: '&#x2229;',
    glyph: '∩',
    latex: '\\cap',
    name: 'cap',
  },
  {
    character: '&#x22C2;',
    glyph: '⋂',
    latex: '\\cap',
    name: 'big cap',
  },
  {
    character: '&#x222A;',
    glyph: '∪',
    latex: '\\cup',
    name: 'cup',
  },
  {
    character: '&#x22C3;',
    glyph: '⋃',
    latex: '\\cup',
    name: 'big cup',
  },
  {
    character: '&#x222B;',
    glyph: '∫',
    latex: '\\int',
    name: 'integral',
  },
  {
    character: '&#x222E;',
    glyph: '∮',
    latex: '\\oint',
    name: 'line integral',
  },
  {
    character: '&#x2202;',
    glyph: '∂',
    latex: '\\partial',
    name: 'partial derivative',
  },
  {
    character: '&#x2207;',
    glyph: '∇',
    latex: '\\nabla',
    name: 'nabla as gradient',
  },
  {
    character: '&#xB1;',
    glyph: '±',
    latex: '\\pm',
    name: 'plus or minus',
  },
  {
    character: '&#x2205;',
    glyph: '∅',
    latex: '\\oslash',
    name: 'emptyset',
  },
  {
    character: '&#x2135;',
    glyph: 'ℵ',
    latex: '\\aleph',
    name: 'aleph',
  },
  {
    character: '&#x2234;',
    glyph: '∴',
    latex: '\\therefore',
    name: 'therefore',
  },
  {
    character: '&#x2235;',
    glyph: '∵',
    latex: '\\because',
    name: 'because',
  },
  {
    character: '&#x22EE;',
    glyph: '⋮',
    latex: '\\vdots',
    name: 'vertical dots',
  },
  {
    character: '&#x22F1;',
    glyph: '⋱',
    latex: '\\ddots',
    name: 'diagonal dots',
  },
  {
    character: '&#x2220;',
    glyph: '∠',
    latex: '\\angle',
    name: 'angle',
  },
  {
    character: '&#x2322;',
    glyph: '⌢',
    latex: '\\frown',
    name: 'frown',
  },
  {
    character: '&#x25B3;',
    glyph: '△',
    latex: '\\triangle',
    name: 'triangle',
  },
  {
    character: '&#x22C4;',
    glyph: '⋄',
    latex: '\\diamond',
    name: 'diamond',
  },
  {
    character: '&#x25A1;',
    glyph: '□',
    latex: '\\square',
    name: 'square',
  },
  {
    character: '&#x2102;',
    latex: 'CC',
    name: '\\mathbb{C}',
  },
  {
    character: '&#x2115;',
    latex: '\\mathbb{N}',
    name: 'natural set',
  },
  {
    character: '&#x211A;',
    latex: '\\mathbb{Q}',
    name: 'rational set',
  },
  {
    character: '&#x211D;',
    latex: '\\mathbb{R}',
    name: 'real set',
  },
  {
    character: '&#x2124;',
    latex: '\\mathbb{Z}',
    name: 'integer set',
  },
  {
    character: '&#xAC;',
    glyph: '¬',
    latex: '\\neg',
    name: 'not',
  },
  {
    character: '&#x21D2;',
    glyph: '⇒',
    latex: '=>',
    name: '\\implies',
  },
  {
    character: '&#x21D4;',
    glyph: '⇔',
    latex: '\\iff',
    name: 'if and only if',
  },
  {
    character: '&#x2200;',
    glyph: '∀',
    latex: '\\forall',
    name: 'for all',
  },
  {
    character: '&#x2203;',
    glyph: '∃',
    latex: '\\exists',
    name: 'exists',
  },
  {
    character: '&#xA0;',
    glyph: ' ',
    latex: '\\textrm{ }',
    name: 'empty space',
  },
];
